# version: "3.8"

#docker run --name mysqldb --network springboot-mysql-net
#  -e MYSQL_ROOT_PASSWORD=root
#  -e MYSQL_DATABASE=user_management
#  -d mysql
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_management
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure


networks:
  springboot-mysql-net: